<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contact_book extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contact_book_model');
    } 

    /*
     * Listing of contact_book
     */
    function index()
    {
        $data['contact_book'] = $this->Contact_book_model->get_all_contact_book();
        
        $data['_view'] = 'contact_book/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contact_book
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Address','Address','required');
		$this->form_validation->set_rules('No_Telp','No Telp','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'No_Telp' => $this->input->post('No_Telp'),
				'user_id' => $this->input->post('user_id'),
				'Address' => $this->input->post('Address'),
            );
            
            $contact_book_id = $this->Contact_book_model->add_contact_book($params);
            redirect('contact_book/index');
        }
        else
        {            
            $data['_view'] = 'contact_book/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a contact_book
     */
    function edit($id_contactbook)
    {   
        // check if the contact_book exists before trying to edit it
        $data['contact_book'] = $this->Contact_book_model->get_contact_book($id_contactbook);
        
        if(isset($data['contact_book']['id_contactbook']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Address','Address','required');
			$this->form_validation->set_rules('No_Telp','No Telp','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'No_Telp' => $this->input->post('No_Telp'),
					'user_id' => $this->input->post('user_id'),
					'Address' => $this->input->post('Address'),
                );

                $this->Contact_book_model->update_contact_book($id_contactbook,$params);            
                redirect('contact_book/index');
            }
            else
            {
                $data['_view'] = 'contact_book/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contact_book you are trying to edit does not exist.');
    } 

    /*
     * Deleting contact_book
     */
    function remove($id_contactbook)
    {
        $contact_book = $this->Contact_book_model->get_contact_book($id_contactbook);

        // check if the contact_book exists before trying to delete it
        if(isset($contact_book['id_contactbook']))
        {
            $this->Contact_book_model->delete_contact_book($id_contactbook);
            redirect('contact_book/index');
        }
        else
            show_error('The contact_book you are trying to delete does not exist.');     
    }
    
}
