<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contact_book_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contact_book by id_contactbook
     */
    function get_contact_book($id_contactbook)
    {
        return $this->db->get_where('contact_book',array('id_contactbook'=>$id_contactbook))->row_array();
    }
        
    /*
     * Get all contact_book
     */
    function get_all_contact_book()
    {
        $this->db->order_by('id_contactbook', 'desc');
        return $this->db->get('contact_book')->result_array();
    }
        
    /*
     * function to add new contact_book
     */
    function add_contact_book($params)
    {
        $this->db->insert('contact_book',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contact_book
     */
    function update_contact_book($id_contactbook,$params)
    {
        $this->db->where('id_contactbook',$id_contactbook);
        return $this->db->update('contact_book',$params);
    }
    
    /*
     * function to delete contact_book
     */
    function delete_contact_book($id_contactbook)
    {
        return $this->db->delete('contact_book',array('id_contactbook'=>$id_contactbook));
    }
}
